// svelte-parent-app/imports/ui/Foods.svelte
<script>
    import { FoodsCollection } from "/imports/db/FoodsCollection";
    import Food from "/imports/ui/Food";

    let foods = [];

    $m: {
        foods = FoodsCollection.find({}).fetch();
    }


</script>

<div>
    <h2>
        Foods Collection:
    </h2>
    <ul>
        {#each foods as food}
            <Food key={food._id} food = {food} />
        {/each}
    </ul>
</div>

// react-child-app/imports/ui/Foods.jsx
import React from "react";
import { FoodsCollection } from "/public/sharedCollections";
import { Food } from "/imports/ui/Food";

export const Foods = () => {
  const foods = FoodsCollection.find({}).fetch();

  const deleteFood = ({ _id }) => {
    FoodsCollection.remove(_id);
  };
  return (
    <div>
      <h2>Foods Collection:</h2>
      <ul>
        {foods.map((food) => (
          <Food key={food._id} food={food} onDeleteClick={deleteFood} />
        ))}
      </ul>
    </div>
  );
};
