// react-child-app/imports/ui/Counter.jsx
import React from "react";
import { useGlobalState } from "state-pool";

export const Counter = () => {
  const [count, setCount] = useGlobalState("count");

  return (
    <div>
      <h2>The current count is: {count}</h2>
      <button
        onClick={() => {
          setCount(count + 1);
        }}
      >
        +
      </button>

      <button
        onClick={() => {
          setCount(count - 1);
        }}
      >
        -
      </button>
    </div>
  );
};

// svelte-parent-app/imports/ui/Counter.svelte
<script>
    import {count} from "/imports/api/stores";
</script>

<div>
    <h2>The current count is: {$count}</h2>
    <button
      on:click={() => {
        count.set($count + 1);
      }}
    >
      +
    </button>

    <button
      on:click={() => {
        count.set($count - 1);
      }}
    >
      -
    </button>
</div>
